In [1]:
import numpy as np

Run to create pdf: `jupyter nbconvert '{title}.ipynb' --to=pdf --output={pdffilename}`

## Question 1

Use NumPy to create a 10x10 array that contains the multiplication table.  Show the code to create the array. Use the `outer` function to create the array.

In [2]:
x = np.arange(1,11)
y = np.arange(1,11)
ans1 = np.multiply.outer(x,y)
print(ans1)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## Question 2

Write code that selects the 4x4 array that's in the middle of the 10x10 array

In [3]:
ans2 = ans1[3:7,3:7]
print(ans2)

[[16 20 24 28]
 [20 25 30 35]
 [24 30 36 42]
 [28 35 42 49]]


## Question 3

Using `arange` and `reshape`, create a 4x4 array with numbers 1 thru 16

In [4]:
a = np.arange(1,17)
ans3 = a.reshape((4,4))
print(ans3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Question 4

Consider the arrays from the last two questions. Create a new 4x4 array that has value of true if both values in the two arrays are even and false otherwise. Hint: use a vectorized custom function with two inputs.

In [5]:
ans4 = np.vectorize(lambda x,y : (x % 2) + (y % 2) == 0)(ans2,ans3)
print(ans4)

[[False  True False  True]
 [False False False False]
 [False  True False  True]
 [False False False False]]


## Question 5

Write code that returns the number of even numbers in the array from Q2.

In [6]:
ans5 = (ans2 % 2 == 0).sum()
print(ans5)

12


## Question 6

Write code the returns the square root of the numbers in the array from Q3.

In [7]:
ans6 = ans3 ** .5
print(ans6)

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]


## Question 7

Write code that returns the array from Q1, where the numbers on the diagonal are incremented by 1. Do not explicitly enumerate all the elements on the diagonal.

In [8]:
ans7 = ans1 + np.eye(10, dtype='int32')
print(ans7)

[[  2   2   3   4   5   6   7   8   9  10]
 [  2   5   6   8  10  12  14  16  18  20]
 [  3   6  10  12  15  18  21  24  27  30]
 [  4   8  12  17  20  24  28  32  36  40]
 [  5  10  15  20  26  30  35  40  45  50]
 [  6  12  18  24  30  37  42  48  54  60]
 [  7  14  21  28  35  42  50  56  63  70]
 [  8  16  24  32  40  48  56  65  72  80]
 [  9  18  27  36  45  54  63  72  82  90]
 [ 10  20  30  40  50  60  70  80  90 101]]


## Question 8

Write code that shows the array from Q1 in reverse order. The first row should have the number 100, 90,...10. The second row should be the ninth row in the initial array in reverse order and so on.

In [9]:
ans8 = np.flip(ans1)
print(ans8)

[[100  90  80  70  60  50  40  30  20  10]
 [ 90  81  72  63  54  45  36  27  18   9]
 [ 80  72  64  56  48  40  32  24  16   8]
 [ 70  63  56  49  42  35  28  21  14   7]
 [ 60  54  48  42  36  30  24  18  12   6]
 [ 50  45  40  35  30  25  20  15  10   5]
 [ 40  36  32  28  24  20  16  12   8   4]
 [ 30  27  24  21  18  15  12   9   6   3]
 [ 20  18  16  14  12  10   8   6   4   2]
 [ 10   9   8   7   6   5   4   3   2   1]]


## Question 9

Write code that creates a 10x10 array of random float numbers between 0.0 and 10.0. The numbers should appear in the array sorted in ascending order.

In [21]:
a = np.random.uniform(low=0.0, high=10.0, size=(100,)) 
ans9 = np.sort(a).reshape((10,10))
print(ans9)

[[0.09112161 0.11059639 0.14994106 0.20598966 0.21922935 0.23828647
  0.31573375 0.75071538 0.86920254 0.88681184]
 [0.96393631 1.13508619 1.19583752 1.69706812 1.72134899 1.76740704
  1.80986052 1.88448049 1.9346782  1.94309675]
 [1.96391198 2.15354727 2.28695054 2.30260146 2.36398964 2.5820733
  3.15427425 3.27749212 3.29302336 3.32218406]
 [3.53785894 3.57694446 3.70822079 3.74716553 3.74921439 3.92537635
  4.01668306 4.13376799 4.1649785  4.22812674]
 [4.26699739 4.27920958 4.29800189 4.39602967 4.41849637 4.43441847
  4.49932368 4.65651896 4.68811113 4.72838415]
 [4.76278799 4.88421209 4.96769786 5.16871675 5.21429181 5.2586894
  5.3257551  5.60180667 5.66866011 5.93397833]
 [5.95111731 5.97725778 6.11548379 6.15403517 6.18466888 6.28355523
  6.44991297 6.5156358  6.75680772 6.94222529]
 [7.05213774 7.29248432 7.31748968 7.46015374 7.48918088 7.6135777
  7.79693436 7.87917233 7.879815   7.98448418]
 [8.10443862 8.12506761 8.14560852 8.39257435 8.55765782 8.76096977
  8.81715726 9.

## Question 10

Write code that creates one-dimensional array of 10 elements. The i th element should be the average of the numbers in the i th row of the array from Q1.

In [11]:
ans10 = ans1.mean(axis=1)
print(ans10)

[ 5.5 11.  16.5 22.  27.5 33.  38.5 44.  49.5 55. ]


## Question 11

Write a method that performs merge sort. Use `partition`, `split`, recursion, and the `hstack` method.

In [12]:
def merge_sort(arr):
    if len(arr) == 1:
        return arr
    mid = len(arr) // 2
    arr = np.partition(arr, [mid])
    l,r = np.split(arr, [mid])
    return np.hstack((merge_sort(l),merge_sort(r)))

a = np.array([1,7,2,0,9,8,6,3,4,5])
ans11 = merge_sort(a)
print(ans11)

[0 1 2 3 4 5 6 7 8 9]
