In [2]:
import numpy as np

# Creating arrays
a
: A 2D array made from a 2D python list

b
: An array of all zeros with length 10 (dtype ensures they're int types)

c
: A 3x5 array full with 2s

d
: An array from 0 to 20 stepping by 2

e
: An array from 0 to 1 with 11 elements stepping by equal amounts

f
: A 3x3 array of random float values between 0 and 1

g
: A 3x3 array with mean 0 and standard deviation 1

h
: A 3x3 array with random ints between 0 and 10

i
: A 3x3 identity matrix

j
: A diagonal array with the diagonal using the given python list

In [6]:
a = np.array([[1,2],[3,4]])
b = np.zeros(10, dtype=int) # there's also np.ones()
c = np.full((3,5), 2)
d = np.arange(0, 20, 2)
e = np.linspace(0, 1, 11)
f = np.random.random((3,3))
g = np.random.normal(0, 1, (3,3))
h = np.random.randint(0, 10, (3,3))
i = np.eye(3)
j = np.diag([1,2,3,4])

print('a:', a, '\nb:', b, '\nc:', c, '\nd:', d, '\ne:', e, '\nf:', f, '\ng:', g, '\nh:', h, '\ni:', i, '\nj:', j, sep='\n')

a:
[[1 2]
 [3 4]]

b:
[0 0 0 0 0 0 0 0 0 0]

c:
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]

d:
[ 0  2  4  6  8 10 12 14 16 18]

e:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

f:
[[0.6127668  0.61003876 0.01173727]
 [0.44706986 0.95584809 0.12928254]
 [0.69558506 0.64846561 0.2107225 ]]

g:
[[-0.55628479 -0.62103538 -0.80432629]
 [ 0.41468867  0.43566954 -0.09777439]
 [-0.39859173  0.72056404  1.50251151]]

h:
[[3 9 8]
 [4 0 5]
 [2 2 7]]

i:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

j:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# Main Data Types
- bool
- ints
    - int8
    - int16
    - int32
    - int64 (long)
- unsigned ints
    - uint8
    - uint16
    - uint32
    - uint64 (long)
- floats
    - float16
    - float32
    - float64 (double)

# Array characteristics
- Shape
: Length of each dimension of the matrix
- Size
: Number of elements in the matrix
- ndim
: Number of dimensions of the matrix
- dtype
: Data type of matrix (see above)

In [7]:
a = np.random.randint(10, size=(2,3))
b = np.random.randint(10, size=6)
c = np.random.randint(100, size=(10,10,10))

print('shape:', a.shape, b.shape, c.shape)
print('size:', a.size, b.size, c.size)
print('ndim:', a.ndim, b.ndim, c.ndim)
print('dtype:', a.dtype, b.dtype, c.dtype)

shape: (2, 3) (6,) (10, 10, 10)
size: 6 6 1000
ndim: 2 1 3
dtype: int64 int64 int64


# Array Indexing
a
: Row 1, column 2

b
: Row 0, column 0

c
: Last row, last column

d
: Row 1 (equivalent to `x[1,::]` and `x[1]`)

e
: Column 2

f
: Rows 0 and 1

g
: Rows in reverse order

h
: Row 0, Column 1 and Row 1, Column 1 as a 2x1 array

In [8]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])


print('a:', x[1,2],
    '\nb:', x[0,0],
    '\nc:', x[-1,-1],
    '\nd:', x[1,:],
    '\ne:', x[:,2],
    '\nf:', x[:2],
    '\ng:', x[::-1],
    '\nh:', x[0:2:1,1:2:1], sep='\n')

a:
6

b:
1

c:
9

d:
[4 5 6]

e:
[3 6 9]

f:
[[1 2 3]
 [4 5 6]]

g:
[[7 8 9]
 [4 5 6]
 [1 2 3]]

h:
[[2]
 [5]]
